-- AlterTable
ALTER TABLE "Cita" ADD COLUMN     "pais" TEXT NOT NULL DEFAULT 'ES',
ADD COLUMN     "personas" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "precio" DOUBLE PRECISION,
ADD COLUMN     "prefijo" TEXT NOT NULL DEFAULT '+34';
